Development
eastgenomics/eggd_expected_depth pull request #1
Opened 2020-02-18 12:50 UTC by Addy81

it works.

2020-02-19 09:27 UTC, Yu-jinKim reviewed
You can probably get rid of some unused scripts in the ccbg toolbox like slurmer.py, db.py etc..
Just to keep things simple, but not a priority right now.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-:-M0Rkvvl4zja58AzQsTK:b792ps2)* status: all files reviewed, 3 unresolved discussions (waiting on @Addy81)

___
*[dxapp.json, line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0RilzU8fvtiTg4wu1Q:-M0RilzU8fvtiTg4wu1R:btgwoqe) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/dxapp.json#L5)):*
> ```JSON
>   "title": "expected_depth_v1.0.0",
>   "summary": "Calculates the expected depth per gene for a whole run.",
>   "tags":["Coverage"],
> ```

You should add the tag to https://cuhbioinformatics.atlassian.net/wiki/spaces/KNOW/pages/690814984/List+of+dxapp.json+tags+for+DNAnexus+apps
___
*[resources/usr/bin/ccbg/af.py, line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0RjblI1mAETLIu23wF:-M0RjblI1mAETLIu23wG:bnrj07g) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/resources/usr/bin/ccbg/af.py#L3)):*
> ```Python
> import sys
> 
> sys.path.append("/software/dev/lib//python2.7/site-packages/")
> ```

I'm surprised this line doesn't raise an error
___
*[resources/usr/bin/ccbg/af.py, line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0Rjt145v9MgV2Tl_aZ:-M0Rjt145v9MgV2Tl_a_:b7vslby) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/resources/usr/bin/ccbg/af.py#L44)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> def latest_file( directory ):
>     """ Find the files, sorted by name and version, in a directory
> 
>     Args:
>       directory(str): directory to look in
> 
>     Returns:
>       dict of lists of filenames and their versions
> 
>     """
>     pass
> ```
</details>


Probably can get rid of this function tbh


<!-- Sent from Reviewable.io -->

2020-03-19 12:07 UTC, mattgarner requested changes

2020-03-19 12:07 UTC, mattgarner commented on resources/usr/bin/ccbg/__init__.py
> +__version__ = "1.3.0"
Why is the version here different to the app version? If this is just leftover from the original pipeline we should remove the version from this file to avoid confusion (I guess you are just using __init_ to enable the other scripts here to be imported?)

2020-03-19 12:07 UTC, mattgarner commented on resources/usr/bin/ccbg/af.py
> +    print( af_vcf("1", 721694,  "A", "G", "/data/projects/matt/brca/data/ExAC.r0.3.1.sites.vep.vcf.gz"))
Is this leftover from testing? Does it have a purpose in the final app?

2020-03-19 12:07 UTC, mattgarner commented on resources/usr/bin/ccbg/slurmer.py
> +    job_status = []
Is this script still used, given that we're not using slurm on AWS?

2020-04-07 10:58 UTC, Addy81 commented on resources/usr/bin/ccbg/af.py
> +    print( af_vcf("1", 721694,  "A", "G", "/data/projects/matt/brca/data/ExAC.r0.3.1.sites.vep.vcf.gz"))
This is from whoever made the app, I didn't make any major changes to the original code.

2020-04-07 14:09 UTC, Addy81 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1)* status: all files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[dxapp.json, line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0RilzU8fvtiTg4wu1Q:-M0RpTcnD8acn5HVDsxf:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/dxapp.json#L5)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

You should add the tag to https://cuhbioinformatics.atlassian.net/wiki/spaces/KNOW/pages/690814984/List+of+dxapp.json+tags+for+DNAnexus+apps
</blockquote></details>

Done.
___
*[resources/usr/bin/ccbg/__init__.py, line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0NLM1ppF9DROpDtGAt-r1-1:-M4JxjPO8iHJU7DKp_hh:bb25ce) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/resources/usr/bin/ccbg/__init__.py#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Why is the version here different to the app version? If this is just leftover from the original pipeline we should remove the version from this file to avoid confusion (I guess you are just using __init_ to enable the other scripts here to be imported?)
</blockquote></details>

App is functional. Nice to have code review to be done in the future to expedite the workflow.
___
*[resources/usr/bin/ccbg/af.py, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0S91cq2BQPvZ0dS8Dz:-M0S91cq2BQPvZ0dS8E-:bo3ulkq) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/resources/usr/bin/ccbg/af.py#L2)):*
> ```
> sys.path.append("/software/dev/lib//python2.7/site-packages/")
> ```
___
*[resources/usr/bin/ccbg/af.py, line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0RjblI1mAETLIu23wF:-M4JyFt07PKJhhF90jn_:b32w0x) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/resources/usr/bin/ccbg/af.py#L3)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I'm surprised this line doesn't raise an error
</blockquote></details>

OK
___
*[resources/usr/bin/ccbg/af.py, line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0Rjt145v9MgV2Tl_aZ:-M4Jy9HbE9dqJU5pjy9Z:bb25ce) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/resources/usr/bin/ccbg/af.py#L44)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

> ```
> def latest_file( directory ):
>     """ Find the files, sorted by name and version, in a directory
> 
>     Args:
>       directory(str): directory to look in
> 
>     Returns:
>       dict of lists of filenames and their versions
> 
>     """
>     pass
> ```

Probably can get rid of this function tbh
</blockquote></details>

App is functional. Nice to have code review to be done in the future to expedite the workflow.
___
*[resources/usr/bin/ccbg/slurmer.py, line 139 at r1](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-M0NLM1ppF9DROpDtGAx-r1-139:-M4JyBwWDyqiFSnYIsE7:b4z1fmv) ([raw file](https://github.com/eastgenomics/eggd_expected_depth/blob/91ec7c8ff163eefed5220050cc936f5deac61a1e/resources/usr/bin/ccbg/slurmer.py#L139)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this script still used, given that we're not using slurm on AWS?
</blockquote></details>

Will check in the future. App is functional. Nice to have code review to be done in the future to expedite the workflow.


<!-- Sent from Reviewable.io -->

2020-04-07 15:29 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1)* status: all files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2020-04-07 15:30 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_expected_depth/1#-:-M4KFqNuDTB2-klS_85K:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2020-04-07 15:30 UTC, merged